# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, default=123456, max_length=30, verbose_name='\u624b\u673a\u53f7\u7801'),
            preserve_default=False,
        ),
    ]
