# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161117_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, max_length=11, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
