# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u9996\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('wechat', models.CharField(blank=True, max_length=255, verbose_name='\u5fae\u4fe1')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='\u5730\u5740')),
                ('wechat_qrcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': '\u5173\u4e8e\u6211\u4eec',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageSubjectItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='\u4e3b\u9898')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u76ee\u5f55\u5bfc\u822a\u9875\u9762',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('techType', models.IntegerField(choices=[(0, '\u8bf7\u9009\u62e9\u6280\u672f\u65b0\u95fb\u7c7b\u578b'), (1, '\u70b9\u64ad'), (2, '\u76f4\u64ad'), (3, '\u64ad\u653e\u5668'), (4, 'CDN'), (5, '\u7f16\u89e3\u7801'), (6, '\u5b58\u50a8'), (7, '\u52a0\u5bc6'), (8, '\u5b89\u5168')], default=0)),
                ('providerType', models.IntegerField(choices=[(0, '\u8bf7\u9009\u62e9\u670d\u52a1\u5546\u65b0\u95fb\u7c7b\u578b'), (1, '\u963f\u91cc\u4e91'), (2, '\u817e\u8baf\u4e91'), (3, '\u91d1\u5c71\u4e91'), (4, '\u4e50\u89c6\u4e91'), (5, '\u4e03\u725b')], default=0)),
                ('sectorType', models.IntegerField(choices=[(0, '\u8bf7\u9009\u62e9\u884c\u4e1a\u65b0\u95fb\u7c7b\u578b'), (1, '\u653f\u7b56'), (2, '\u8d44\u672c'), (3, '\u4f1a\u8bae')], default=0)),
                ('caseType', models.IntegerField(choices=[(0, '\u8bf7\u9009\u62e9\u5e94\u7528\u65b0\u95fb\u7c7b\u578b'), (1, '\u79c0\u573a'), (2, '\u6e38\u620f'), (3, '\u5728\u7ebf\u6559\u80b2'), (4, '\u65b0\u5a92\u4f53'), (5, '\u89c6\u9891\u4f1a\u8bae'), (6, '\u76d1\u63a7')], default=0)),
                ('practitionerType', models.IntegerField(choices=[(0, '\u8bf7\u9009\u62e9\u4ece\u4e1a\u8005\u65b0\u95fb\u7c7b\u578b'), (1, '\u8425\u9500'), (2, '\u5e02\u573a'), (3, '\u4ea7\u54c1'), (4, '\u8fd0\u8425'), (5, '\u6d4b\u8bd5'), (6, '\u5f00\u53d1'), (7, '\u6280\u672f\u652f\u6301')], default=0)),
            ],
            options={
                'verbose_name': '\u8d44\u8baf\u5185\u5bb9\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u8d44\u8baf\u9996\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PractitionerIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u4ece\u4e1a\u8005\u9996\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProviderNewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5546\u9996\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectorNewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u884c\u4e1a\u9996\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u9996\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TechNewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u8d44\u8baf\u9996\u9875',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestPlatformPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u7edf\u4e00\u6d4b\u8bd5\u5e73\u53f0\u9875\u9762',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoProduction',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u62cd\u6444\u5236\u4f5c\u9875\u9762',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoProductionIntroduceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='\u4e3b\u9898')),
                ('desc', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_items', to='home.VideoProduction')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '\u5165\u53e3\u9875\u9762'},
        ),
        migrations.AddField(
            model_name='homepagesubjectitems',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_index_items', to='home.HomePage'),
        ),
    ]
