# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0003_auto_20161104_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagerelatedlink',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '\u5165\u53e3\u9875\u9762'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='entry_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepagesubjectitems',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_index_items', to='home.HomePage'),
        ),
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
        migrations.DeleteModel(
            name='HomePageRelatedLink',
        ),
    ]
