# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161203_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('indexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.IndexPage')),
            ],
            options={
                'verbose_name': '\u52a8\u6001',
            },
            bases=('home.indexpage',),
        ),
    ]
