# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161109_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproductionintroduceitem',
            name='desc',
        ),
        migrations.AddField(
            model_name='videoproductionintroduceitem',
            name='content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u89c6\u9891\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='videoproductionintroduceitem',
            name='url',
            field=models.URLField(blank=True, verbose_name='\u89c6\u9891\u5185\u5bb9\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='videoproductionintroduceitem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='videoproductionintroduceitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u6807\u9898'),
        ),
    ]
