# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0004_eventindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('embed_url', models.URLField(blank=True, verbose_name='\u94fe\u63a5URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeepShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005\u540d\u79f0')),
                ('title', models.CharField(max_length=255, verbose_name='\u4ece\u4e1a\u8005title')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='home.CareerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='casepagevideoitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='casepagevideoitem',
            name='page',
        ),
        migrations.DeleteModel(
            name='CasePageVideoItem',
        ),
    ]
