# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.Fields
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0004_contentpage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u6848\u4f8b\u9875\u9762',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CasePageCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('embed_url', models.URLField(blank=True, verbose_name='\u94fe\u63a5URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasePageVideoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='\u7f29\u7565\u56fe')),
                ('content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='\u89c6\u9891\u5185\u5bb9')),
                ('url', models.URLField(blank=True, verbose_name='\u89c6\u9891\u94fe\u63a5\u5730\u5740')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_items', to='home.CasePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': '\u89e3\u51b3\u65b9\u6848\u9875\u9762',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'h2', wagtail.wagtailcore.blocks.CharBlock(classname=b'title', icon=b'title')), (b'h3', wagtail.wagtailcore.blocks.CharBlock(classname=b'title', icon=b'title')), (b'h4', wagtail.wagtailcore.blocks.CharBlock(classname=b'title', icon=b'title')), (b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon=b'pilcrow', label='\u7b80\u4ecb')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon=b'pilcrow', label='\u6bb5\u843d')), (b'aligned_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='\u8bf7\u9009\u62e9\u56fe\u7247')), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock()), (b'alignment', home.Fields.ImageFormatChoiceBlock())], icon=b'image', label='\u56fe\u7247')), (b'pullquote', wagtail.wagtailcore.blocks.StructBlock([(b'quote', wagtail.wagtailcore.blocks.TextBlock(label='\u5f15\u7528\u6b63\u6587')), (b'attribution', wagtail.wagtailcore.blocks.CharBlock(label='\u5f15\u7528\u81ea'))], label='\u5f15\u8a00')), (b'aligned_html', wagtail.wagtailcore.blocks.StructBlock([(b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'alignment', home.Fields.HTMLAlignmentChoiceBlock())], icon=b'code', label='HTML \u4ee3\u7801')), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon=b'doc-full-inverse', label='\u8bf7\u9009\u62e9\u6587\u672c'))]),
        ),
        migrations.AddField(
            model_name='casepagecarouselitem',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='casepagecarouselitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='home.CasePage'),
        ),
    ]
