# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161106_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': '\u8d44\u8baf\u9996\u9875'},
        ),
        migrations.AlterModelOptions(
            name='technewsindexpage',
            options={'verbose_name': '\u6280\u672f\u8d44\u8baf\u9996\u9875'},
        ),
        migrations.AlterModelOptions(
            name='technewspage',
            options={'verbose_name': '\u8d44\u8baf\u5185\u5bb9\u9875'},
        ),
    ]
