# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161107_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': '\u5173\u4e8e\u6211\u4eec'},
        ),
    ]
