# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0005_auto_20161126_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('menu_priority', models.SmallIntegerField(blank=True, verbose_name='\u76ee\u5f55\u6743\u91cd')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
