# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0005_auto_20161203_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageProviderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='\u4f9b\u5e94\u5546')),
                ('embed_url', models.URLField(blank=True, verbose_name='\u94fe\u63a5URL')),
                ('products', wagtail.wagtailcore.fields.RichTextField(verbose_name='\u4e3b\u8981\u4ea7\u54c1')),
                ('customers', wagtail.wagtailcore.fields.RichTextField(verbose_name='\u5ba2\u6237\u65b9\u5411')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='home.IndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
