# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0006_indexpageprovideritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepage',
            name='co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
