# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161107_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributepage',
            options={'verbose_name': '\u89c6\u9891\u5168\u5a92\u4f53\u5206\u53d1'},
        ),
    ]
