# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0006_menupage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MenuPage',
        ),
    ]
