# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161127_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
    ]
