# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0007_casepage_co'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePageCaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('intro', models.CharField(blank=True, max_length=255, verbose_name='\u7b80\u4ecb')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u540d\u79f0')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasePageVideoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('url', models.URLField(blank=True, verbose_name='\u89c6\u9891\u94fe\u63a5\u5730\u5740')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='casepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='casepagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='casepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='casepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='casepage',
            name='co',
        ),
        migrations.DeleteModel(
            name='CasePageCarouselItem',
        ),
        migrations.AddField(
            model_name='casepagevideoitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_videos', to='home.CasePage'),
        ),
        migrations.AddField(
            model_name='casepagecaseitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_items', to='home.CasePage'),
        ),
    ]
