# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170107_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepagevideoitem',
            name='url',
        ),
        migrations.AddField(
            model_name='casepagevideoitem',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='\u89c6\u9891\u4ee3\u7801'),
            preserve_default=False,
        ),
    ]
