# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_solutionpage_menu_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
        migrations.AddField(
            model_name='navigationpage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='menu_priority',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='\u76ee\u5f55\u6743\u91cd'),
        ),
    ]
