# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170107_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepagevideoitem',
            name='image',
        ),
    ]
