# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_casepagevideoitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepagevideoitem',
            name='code',
            field=wagtail.wagtailcore.fields.RichTextField(max_length=255, verbose_name='\u89c6\u9891\u4ee3\u7801'),
        ),
    ]
