# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170107_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepagevideoitem',
            name='code',
            field=wagtail.wagtailcore.fields.StreamField([(b'code', wagtail.wagtailcore.blocks.RawHTMLBlock())]),
        ),
    ]
